### ISSUE TITLE
election.xml loaded improperly

### ISSUE THREAD

**Issue by umbernhard** [Drazcmd/PsychBallots-StarVote#2]
In the first line of star.js, the xml formatting file election.xml is referenced just as "election.xml". This is a problem, as the file is being loaded off the local machine and the current state can cause the page to crash. It should be addressed as "file:///election.xml", or, if used in a windows application, "ms-appx:///election.xml".

**Comment by Drazcmd** [comment]
To anyone looking at this later - if you're just running it locally using MAMP (and I believe IntelliJ) it needs to be just "election.xml," using "file:///election.xml" won't work; the above comment is mainly in regards to making run as a Windows app. Probably we'll need to end up making two separate branches anyways so we don't end up getting confused by this sort of thing.
